### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by mnery9** [IBM-Bluemix-Docs/cloud-object-storage#11]
The page:
https://console.bluemix.net/docs/services/cloud-object-storage/cli/curl.html

has at least two broken links:
https://console.bluemix.net/docs/services/cloud-object-storage/cli/docs/services/cloud-object-storage/api-reference/api-reference-buckets.html
https://console.bluemix.net/docs/services/cloud-object-storage/cli/docs/services/cloud-object-storage/api-reference/api-reference-objects.html

Also, it does not give any pointers on how to get values like (endpoint), (token), etc on a call like:

```
curl "https://(endpoint)/"
 -H "Authorization: bearer (token)"
 -H "ibm-service-instance-id: (resource-instance-id)"
```

**Comment by nglange** [comment]
Broken links are fixed.  I'll close this ticket when additional links are added to the endpoints and IAM pages.

**Comment by nglange** [comment]
This was updated a while ago but not closed.
