### ISSUE TITLE
'Using Key Protect' section doesn't include sufficient detail to be useful.

### ISSUE THREAD

**Issue by danifitz** [IBM-Bluemix-Docs/cloud-object-storage#16]
Hi,

I'm trying to create a bucket using COS, Key Protect and the Node.js SDK using the [Library > Node.js](https://console.bluemix.net/docs/services/cloud-object-storage/libraries/node.html#using-node-js) docs page I find the explanation of how to do this quite obscure. For example, there should be a better explanation of what each of the fields in the `params` object mean and where you can get the data for those fields. I have managed to figure out most of them but I still don't have working code.

For example, where does one find the `IBMSSEKPCustomerRootKeyCrn`? What is this value? Furthermore, there is no mention that in this page or [Managing Encryption](https://console.bluemix.net/docs/services/cloud-object-storage/basics/encryption.html#manage-encryption) that you can only create Key Protect encrypted buckets when creating a `regional` bucket so I spent 30 minutes debugging my code before realising.

**Comment by nglange** [comment]
You're right, that's confusing.  The example shows all possible fields for a `params` object when creating a bucket, not just the necessary ones.  An update will go into the next build.

**Comment by danifitz** [comment]
@nglange I agree, you should only show the required params. However I also think there needs to be a better explanation of what `IBMSSEKPEncryptionAlgorithm` & `IBMSSEKPCustomerRootKeyCrn` mean and what the possible values could be. Also, how do I find out what my root key crn is? Even if it's just a link to another page which explains how to find out those values.

**Comment by TheRev433** [comment]
Did you get the way to do that? 
I'm trying to user SSE-C, but there is no documentation about that. It just mention the way to send the data using cURL commands, but what about using NodeJS?

**Comment by nglange** [comment]
Good point @TheRev433 - there's not a Node sample for that in the current documentation. There's a new platform for API and SDK samples, but it's not quite done - will be publicly available in the next couple of weeks. 

For SSE-C, it's also just a chunk of additional values to stick into the params object for a request - you can see them here: https://ibm.github.io/ibm-cos-sdk-js/AWS/S3.html#putObject-property

**Comment by TheRev433** [comment]
Hi @nglange.
Sorry if this is not the correct way to do this, but I would like to ask you if, for SSE-C, is enough to include these 3 properties?

-  SSECustomerAlgorithm",
-  SSECustomerKey,
-  SSECustomerKeyMD5

My architect told me that maybe I could need to also add another property just to indicate that I will include an specific key, but we are not quit sure about that.
![image](https://user-images.githubusercontent.com/36829865/109066665-029d0300-76b3-11eb-9232-f87d332e08b3.png)


P.S: The link you provided me was really helpful, thank you so much! :D

**Comment by nglange** [comment]
Nah, any way to get in touch is good for me.  When things get complex we can get the support team involved, but I'm always happy to chat with developers working with object storage.  

Yeah, the only thing is that the `SSECustomerKey` is _not_ the same secret key that is used for HMAC/signature auth, but is really just the encryption key that you are using.  Typically it's base 64 encoded, but it's effectively just an opaque string.  As you have it written, I'd assume a variable called `crypto_secret`.  Does that make sense?

**Comment by TheRev433** [comment]
Thanks for the reply!
Yeah, I think we are not using HMAC, but yeah, the _crypto_secret_ it's just a string, not in Base64, as it throws an error when I pass a Base64 key.

Thanks for all the help!
