### ISSUE TITLE
Python API lacks important functions

### ISSUE THREAD

**Issue by YehonatanBitton** [IBM-Bluemix-Docs/cloud-object-storage#24]
Hello, i'm an early user of the cloud object storage, at the CLI, java, and python.

The python API lacks important functions. For comparison, AWS object storage DO HAVE all of these functions. 

This is the API:
https://ibm.github.io/ibm-cos-sdk-python/reference/services/s3.html#client

1. Update metadata for object - the current solution for the programmer is to use copy_object function with the same key and add the metadata. This solution is bad because it's slowly copies all of the data instead of just adding simple metadata to the object.

2. Getting bucket size - The current solution is to iterate all of the bucket objects (Can take hours...) and sum them. The solution is bad because it takes TOO MUCH TIME to know how many files you have in the bucket. 
As well as the GUI version at IBM Bluemix - don't give you this data. 

3. move_file command. This command is available at the CLI, but not in the python API. The solution is to use copy and delete - which can cause bugs if used inappropriately, and again - SLOWER because it uses two api calls instead of one. 

4. Renaming file. The current solution it to use copy and delete. (Again - too much work for simple outcome. AWS S3 do have this function)

This is only 4 functions I found that are missing, but obviously the Python API should be more complete and comfortable for programmers. Thanks.

**Comment by nglange** [comment]
Thanks for the feedback, I've passed it to the SDK team.  I agree that having the above functionality would be helpful indeed.
