### ISSUE TITLE
ability to upload a complete directory

### ISSUE THREAD

**Issue by MourIdri** [IBM-Bluemix-Docs/cloud-object-storage#3]
Is it possible to had this in the SDK ? : Directory upload

**Comment by nglange** [comment]
@MourIdri Right now the IAM-enabled COS service doesn't support access key / secret key authentication, and thusly doesn't support s3 compatible CLIs and tools.  AWS signature support is coming later this year and then it will be possible to use the AWS CLI / s3cmd / mc / Cyberduck / etc to do directory syncing.
