### ISSUE TITLE
Document link broken

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Bluemix-Docs/cloud-object-storage#33]
Under https://console.bluemix.net/docs/services/cloud-object-storage/basics/encryption.html#sse-kp

The **step b** has a broken link
<img width="845" alt="screen shot 2018-09-04 at 7 26 38 pm" src="https://user-images.githubusercontent.com/6552440/45035839-965c5e00-b078-11e8-8069-61f017033306.png">

**Comment by nglange** [comment]
Fixed, thanks.
