### ISSUE TITLE
Documented "walkthrough" for 'Using a Compatible Tool'

### ISSUE THREAD

**Issue by jamesbeltonIBM** [IBM-Bluemix-Docs/cloud-object-storage#35]
Hi, 
As part of the user-facing documentation that I am involved in creating as part of the IBM Cloud Consumption Team, I have written and published on github a walk-through on connecting to Object Storage, focusing on the 'using a compatible tool' section of this page. To enhance the Cloud Docs page, can I suggest a link to my walk-through guide at https://github.com/jamesbeltonIBM/Connecting-an-s3-API-Compatible-Third-Party-Utility-to-work-with-IBM-Cloud-Object-Storage-

Cheers,
James

**Comment by jamesbeltonIBM** [comment]
I've also had a request from a customer (via a CSM) to add a 'Getting Started' section for 3rd party tools, so again, the guide I created helps with this.  @jenschlot

**Comment by nglange** [comment]
Thanks James, we'll fold this in.

**Comment by nglange** [comment]
This should be available in the next build.
