### ISSUE TITLE
How-to guide for the Allowing Public Access Page

### ISSUE THREAD

**Issue by jamesbeltonIBM** [IBM-Bluemix-Docs/cloud-object-storage#36]
Hi, I have created a how-to guide that complements the Allowing Public Access page (https://console.bluemix.net/docs/services/cloud-object-storage/iam/public-access.html#allowing-public-access). It gives a walkthrough, showing both the cURL and aws CLI methods, with examples and where to find / create the necessary credentials / endpoints. 
It can be found here https://github.com/jamesbeltonIBM/Making-Objects-Publicly-Available-from-IBM-Cloud-Object-Storage-

**Comment by nglange** [comment]
Thanks James - this is helpful and we'll get the content incorporated.
