### ISSUE TITLE
Issue with Initializing Configuration example

### ISSUE THREAD

**Issue by jamesbeltonIBM** [IBM-Bluemix-Docs/cloud-object-storage#38]
Hi, 
I've been working all morning to get something simple working - a list of my buckets from COS via python script. A couple of things would have helped enormously and got me going in 5 minutes instead of 3 hours!

1) Can you add a couple of lines to the top of the Initializing Configuration example code; namely:
``
import ibm_boto3
from ibm_botocore.client import Config
``
2) For a bit of clarity, can you rename the COS_SERVICE_CRN constant in the code example to something like COS_RESOURCE_CRN? The way it is currently written lead me to use my iam_service_id_crn from my creds, which gave me loads of errors as you would have expected. If the Constant had been named with 'RESOURCE', I'd have used the right credential and saved loads of time. I am not the only one as I've found that a colleague has made the exact same mistake and told me they also spent hours trying to figure it out.

Cheers,
James

**Comment by nglange** [comment]
Thanks, these updates have been made and will show up in the next build.  I know the naming can be confusing.
