### ISSUE TITLE
curl documentation

### ISSUE THREAD

**Issue by Mark-Tyneway** [IBM-Bluemix-Docs/cloud-object-storage#4]
I am trying to access Cloud Object Storage via `curl`
I usually use `curl -u user:pw` to generate the header `Authorization: Basic $(echo "user:pw | base64)` - The documentation here states to use the header `Authorization: bearer (token)`

In some of the examples, it uses `Bearer` and in other examples it uses `bearer`.  If I use `Bearer` or `bearer` instead of `Basic`, I get an `AccessDenied` error.  Should the docs be using `Basic` instead?

**Comment by nglange** [comment]
Sorry Mark - these issues weren't generating the right notifications.  Did you get this sorted out? The way IBM Cloud IAM works with COS is a two-step process:  first the client needs to exchange an API key for a token, and then that token is used to authenticate the user.  We don't support Basic auth at this time.
