### ISSUE TITLE
include hmac additional parameter  '{"HMAC":true}' in docs

### ISSUE THREAD

**Issue by tom342178** [IBM-Bluemix-Docs/cloud-object-storage#40]
The documents state that you need to add an additional parameter to generate the hmac key but then don't say what that parameter is. 
Change: 
Users can create a set of HMAC credentials when creating a Service Credential by providing a configuration parameter during credential creation.
To:
Users can create a set of HMAC credentials when creating a Service Credential by providing the additional '{"HMAC":true}' configuration parameter during credential creation.

**Comment by nglange** [comment]
Thanks, it's been fixed and will be updated in the next deployment.
