### ISSUE TITLE
S3CMD CLI only works with Cross-region buckets

### ISSUE THREAD

**Issue by mgorbat** [IBM-Bluemix-Docs/cloud-object-storage#42]
Prerequisite:
s3cmd has been installed and configured according to instructions [here](https://console.bluemix.net/docs/services/cloud-object-storage/basics/multipart.html#store-very-large-objects)
s3cmd ls command executes well returning the list of the buckets

Problem:
s3cmd ls s3://bucketname is not returning any content and produces the following error message:
> ERROR: Bucket 'bucketname' does not exist
> ERROR: S3 error: 404 (NoSuchBucket): The specified bucket does not exist.
Any attempt to write into the bucket results in subsequent errors.

Solution:
The bucket type has to be **Cross Region**. Any other bucket type will not work with S3CMD. The documentation does not mention any guidance towards the bucket type.

**Comment by nglange** [comment]
Ahh, I see.  The example config is set to a the US Cross Region endpoint.  Editing the config to replace the lines with your desired [endpoint](https://console.bluemix.net/docs/services/cloud-object-storage/basics/endpoints.html):
```
host_base = s3-api.us-geo.objectstorage.softlayer.net
host_bucket = %(bucket)s.s3-api.us-geo.objectstorage.softlayer.net
```
