### ISSUE TITLE
ibm_iam_auth option needs to be specified for using s3fs if creds file only has apikey

### ISSUE THREAD

**Issue by prempiyush** [IBM-Bluemix-Docs/cloud-object-storage#47]
The user needs to explicitly specify ‘ibm_iam_auth’ option to s3fs if the credentials file has only the apikey.

Otherwise this is the error we get: “s3fs: failed to set internal data for access key/secret key from passwd file.”

Can someone please update s3fs.md accordingly?

**Comment by nglange** [comment]
Like this? 

`s3fs <bucket> <mountpoint> -o url=http{s}://<endpoint> –o passwd_file=<credentials_file> -o ibm_iam_auth`

**Comment by prempiyush** [comment]
@nglange Yes, correct. Details are mentioned here https://github.com/s3fs-fuse/s3fs-fuse

**Comment by nglange** [comment]
[Added here](https://github.com/IBM-Bluemix-Docs/cloud-object-storage/commit/d08c4c6c8bbbdf44f4b9a3a55dc8c29d0276efbc).

**Comment by coolmary** [comment]
Thanks for contacting me I will have to program my computers. I'm waiting on GSA GWAC to give me my Fleet Card and provide a Computer as Telework Subcontractors and Prime Contractors Including a Students
