### ISSUE TITLE
It's difficult to determine where to find the information for the config

### ISSUE THREAD

**Issue by mrappard** [IBM-Bluemix-Docs/cloud-object-storage#5]
Where it says

var config = {
endpoint: '<endpoint>',
apiKeyId: '<api-key>',
ibmAuthEndpoint: 'https://iam.ng.bluemix.net/oidc/token',
serviceInstanceId: '<resource-instance-id>',
};

It's difficult to determine where to find the data, specifically the "Service Instance ID." Would it be possible to clarify this in greater detail.

**Comment by nglange** [comment]
Thanks - right now the only way to get that info is via the CLI or by creating a service credential.  It should be more apparent in the console soon.  I'll add some info and links to make it more clear.

**Comment by nglange** [comment]
@mrappard I updated a page to try and make this more clear.  I'll go ahead and close this issue, but let me know if it can be improved further. Thanks!
