### ISSUE TITLE
Using Python COS: Error when retrieving credentials 

### ISSUE THREAD

**Issue by kingaj12** [IBM-Bluemix-Docs/cloud-object-storage#50]
Here I am following the python example [initializing configuration](https://cloud.ibm.com/docs/services/cloud-object-storage/libraries/python.html#init-config).

The credential sample fields don't seem to follow the current IAM apikey configuration.

In the coding example we see:
    
    # Constants for IBM COS values
    COS_ENDPOINT = "<endpoint>" # Current list avaiable at https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints
    COS_API_KEY_ID = "<api-key>"
    COS_AUTH_ENDPOINT = "https://iam.cloud.ibm.com/oidc"
    COS_RESOURCE_CRN = "<resource-instance-id>"
    COS_BUCKET_LOCATION = "<location>"

But the COS service key actually contains:

    {
      "apikey": <>,
      "cos_hmac_keys": {
            "access_key_id": <>,
            "secret_access_key": <>,
          },
      "endpoints": "https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints",
      "iam_apikey_description":<>,
      "iam_apikey_name": <>,
      "iam_role_crn": <>,
      "iam_serviceid_crn": <>,
      "resource_instance_id": <>
    }

Finally, to add frustration to confusion, after trying my best guess at translating the COS key entries to the code example, the code bombs with the message:

    Unable to retrieve file contents: Error when retrieving credentials from https://iam.cloud.ibm.com/oidc: HttpCode(403) - Retrieval of tokens from server failed.

**Comment by kingaj12** [comment]
Follow-on comment - it seems like one should have a function that simply takes the service key and returns a COS resource.  Like

    cos = ibm_boto3.Resource(service_key)

Why not?

**Comment by nglange** [comment]
The IAM issue was fixed a ways back, but added a bit more clarity to the variable names with #57.

Agree that the `Resource()` method should be able to take the service key blob.  It would be helpful to [open an issue directly against the SDK](https://github.com/IBM/ibm-cos-sdk-python/issues).
