### ISSUE TITLE
Endpoint fail in the aws --endpoint-url {endpoint} pattern

### ISSUE THREAD

**Issue by kingaj12** [IBM-Bluemix-Docs/cloud-object-storage#51]
I am trying to use the aws CLI as documented in [https://console.bluemix.net/docs/services/cloud-object-storage/cli/aws-cli.html#use-the-aws-cli](https://console.bluemix.net/docs/services/cloud-object-storage/cli/aws-cli.html#use-the-aws-cli)

But there is a tricky question for the uninitiated .. what is an {endpoint}?  I tried the following

    https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints

which is a good guess since this is the value of "endpoints" in the service credential.  Then I tried the following:

    s3.us-east.cloud-object-storage.appdomain.cloud

which is also a good guess since this is what is in the left panel under "Endpoints", but then you have to guess which endpoint is really meant.

But in either case, I get the message:
    
    Bad value for --endpoint-url "xxxxxxx": scheme is missing.  Must be of the form http://<hostname>/ or https://<hostname>/

Should I be looking elsewhere?

**Comment by lifemikey** [comment]
v2/endpoints is just a programmatic way to query the endpoints. 

You just need    https://S3.us-east... part

**Comment by kingaj12** [comment]
Ah - yes, you mean I should have used 

    --endpoint-url https://s3.us-east.cloud-object-storage.appdomain.cloud

yes that does work!  But now I get

    $ aws --endpoint-url https://s3.us-east.cloud-object-storage.appdomain.cloud s3 ls
    An error occurred (400) when calling the ListBuckets operation: Bad Request
