### ISSUE TITLE
python example code has error

### ISSUE THREAD

**Issue by mdarden** [IBM-Bluemix-Docs/cloud-object-storage#59]
The example code provided [here](https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-using-python#using-python) produces errors out of the box because an import is missing.

`from ibm_botocore.client import Config`
should be 
`from ibm_botocore.client import Config, ClientError`

**Comment by nglange** [comment]
That's a good point.  We recently added a [new sample](https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-getting-started-with-the-sdks&programming_language=python#getting-started-with-the-sdks) that is intended to show what a more realistic bit of code might look like.  The existing examples will likely be retired as they are folded into the larger one, but the `ClientError` import needs to be made more clear.  Thanks for the feedback.

**Comment by nglange** [comment]
Fixed in 8495082d5d81311896df1b59d285f4668af8e12e
