### ISSUE TITLE
Failed to authen Cloud Object Storage with API Key

### ISSUE THREAD

**Issue by Jakkapob** [IBM-Bluemix-Docs/cloud-object-storage#6]
I've deploy Cloud Object Storage service and created services credential. I've develop Node JS application on Linux follow this article and try to create object in the bucket via my application and I face the error AccessDenied: Access Denied. I created the environment varibale in ~/.aws/credentials and get the information from services credential as the input. What should be use as the credential for aws_access_key_id and aws_secret_access_key? For aws_access_key_id I enter "apikey": and aws_secret_access_key "resource_instance_id": but seem like is not correct.

What should be value that enter to aws_access_key_id and aws_secret_access_key ? How can I get it from?

[default]

aws_access_key_id = l8ZLFNERnynY5PN052-PqDK3fUTRj-XROwdj2UfpXq-Y

aws_secret_access_key = crn:v1:bluemix:public:cloud-object-storage:global:a/9f33b227cebface6927b7c57b9a37f29:97f4b026-97f3-4852-b4fe-544c0b759c65::

**Comment by nglange** [comment]
@Jakkapob Are you sure that the identity associated with that API key has the proper IAM permissions?  Did you create the API key by creating a Service Credential?  If so you can use the CLI to check the policies:

1. `bx iam service-ids` will get you a list of Service IDs,
2. `bx iam service-policies <service-id-name>` will show all the policies for that identity.

You'll need to have either `writer` or `manager` roles.

**Comment by nglange** [comment]
Closing the issue, but let me know if changing the permissions via an IAM policy helps.
