### ISSUE TITLE
Aspera SDK for Python

### ISSUE THREAD

**Issue by GitKambiz** [IBM-Bluemix-Docs/cloud-object-storage#61]
We have a large number of CSV files on a SAN drive accessible by Windows 2012 R2 server.
Is there a version of Aspera SDK for Python 3 that we can add to our existing IBM COS SDK for uploading files?

**Comment by nglange** [comment]
The COS SDK supports Aspera transfers for Python 3.6.  See the [docs here](https://cloud.ibm.com/docs/services/cloud-object-storage/libraries?topic=cloud-object-storage-python#python-examples-aspera) for an example.

**Comment by GitKambiz** [comment]
Does it support windows 2012 R2?
