### ISSUE TITLE
element in XML body for POST restore object is incorrect

### ISSUE THREAD

**Issue by charudut** [IBM-Bluemix-Docs/cloud-object-storage#62]
I was referring to https://cloud.ibm.com/docs/services/cloud-object-storage/basics?topic=cloud-object-storage-archive#archive-api-restore and here I saw the element `GlacierJobParameter` in syntax and example, such as
```
<RestoreRequest>
    <Days>3</Days> 
    <GlacierJobParameter>
        <Tier>Bulk</Tier>
    </GlacierJobParameter>
</RestoreRequest>
```

however, this element did not work for me. I always got following error
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
    <Code>MalformedXML</Code>
    <Message>The XML you provided was not well-formed or did not validate against our published schema.</Message>
    <Resource>/bucket2/object1</Resource>
    <RequestId>64ced386-d70f-4684-a554-727cf594a5bf</RequestId>
    <httpStatusCode>400</httpStatusCode>
</Error>
```

I looked up AWS's document https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOSTrestore.html#RESTObjectPOSTrestore-requests and here it mentions the element should be `GlacierJobParameters` and it worked for me.
```
<RestoreRequest>
  <Days>3</Days>
  <GlacierJobParameters>
    <Tier>Bulk</Tier>
  </GlacierJobParameters>
</RestoreRequest>
```

**Comment by nglange** [comment]
Thanks for the catch!  It's been fixed and the change should be reflected shortly.
