### ISSUE TITLE
no such host error

### ISSUE THREAD

**Issue by harryprins** [IBM-Bluemix-Docs/cloud-object-storage#63]
According to the tutorial on /tutorials/migrage, https://identity.open.s3.us-south.cloud-object-storage.appdomain.cloud.com/v3 should be the `auth` value. However, when I run rclone with the configuration, it results in the following error:

> 2019/06/17 17:55:18 Failed to create file system for "TEST:": Post https://identity.open.s3.us-south.cloud-object-storage.appdomain.cloud.com/v3/auth/tokens: dial tcp: lookup identity.open.s3.us-south.cloud-object-storage.appdomain.cloud.com: no such host

**Comment by lifemikey** [comment]
Thanks for pointing this out, will get this fixed.
This is the correct url
https://identity.open.softlayer.com/v3

**Comment by lifemikey** [comment]
This has been fixed
https://cloud.ibm.com/docs/services/cloud-object-storage/tutorials?topic=cloud-object-storage-migrate
