### ISSUE TITLE
List buckets did not work

### ISSUE THREAD

**Issue by vikramkhatri** [IBM-Bluemix-Docs/cloud-object-storage#65]
I followed the instructions. I was able to get the token and get the service id. I had put both in a shell variable and when I run the `list bucket`, I get the error.

```
curl "https://s3.us-east.cloud-object-storage.appdomain.cloud/" \
 -H "Authorization: bearer $TOKEN" \
 -H "ibm-service-instance-id: $SERVICEID"
```

I get 403 error.
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource></Resource><RequestId>1dea4c07-984c-4a0a-9c83-f1c6cad81aea</RequestId><httpStatusCode>403</httpStatusCode></Error>
```

What did I miss?

**Comment by nglange** [comment]
It seems that the identity that made the request didn't have the proper roles on the bucket.  I'll close this for now, but can reopen it if there is a specific topic that could be improved.
