### ISSUE TITLE
'Generating an authorization header' Python example missing prefix '/'

### ISSUE THREAD

**Issue by KyungmoIBM** [IBM-Bluemix-Docs/cloud-object-storage#66]
The sample code fails to establish connection because 'standardized_resource' variable missing prefix '/'. 

Line 41 : standardized_resource = bucket + '/' + object_key

Please add prefix "/" at beginning of the variable, like
```
...
standardized_resource = '/' + bucket + '/' + object_key
standardized_querystring = request_parameters
...
```

Also, please change 'http' tp 'https' at linen 15
endpoint = 'http://s3.us.cloud-object-storage.appdomain.cloud' 
--->
endpoint = 'https://s3.us.cloud-object-storage.appdomain.cloud'

**Comment by nglange** [comment]
Thanks, it's been updated and should appear in production shortly.
