### ISSUE TITLE
Misspelled title, please correct

### ISSUE THREAD

**Issue by DougAtIBM** [IBM-Bluemix-Docs/cloud-object-storage#7]
https://github.com/IBM-Bluemix-Docs/cloud-object-storage/blob/96963d9d2c3610268bcafa200e145dcf68cce0e6/info/data-security-encryption.md

**Comment by nglange** [comment]
😬  https://github.com/IBM-Bluemix-Docs/cloud-object-storage/commit/c636464c165a0616d15d25180d5f4d3e4da23910

**Comment by DougAtIBM** [comment]
Hi, encryption is not spelled encyrption ;-)

**Comment by nglange** [comment]
Yep - it's fixed in the commit linked above.  Takes a while for the build process to get it up into production.  Thanks!
